/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/edmondshtogu/argocd-client/pkg/apis/v1alpha1"
	scheme "github.com/edmondshtogu/argocd-client/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ApplicationSetsGetter has a method to return a ApplicationSetInterface.
// A group's client should implement this interface.
type ApplicationSetsGetter interface {
	ApplicationSets(namespace string) ApplicationSetInterface
}

// ApplicationSetInterface has methods to work with ApplicationSet resources.
type ApplicationSetInterface interface {
	Create(ctx context.Context, applicationSet *v1alpha1.ApplicationSet, opts v1.CreateOptions) (*v1alpha1.ApplicationSet, error)
	Update(ctx context.Context, applicationSet *v1alpha1.ApplicationSet, opts v1.UpdateOptions) (*v1alpha1.ApplicationSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ApplicationSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ApplicationSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ApplicationSet, err error)
	ApplicationSetExpansion
}

// applicationSets implements ApplicationSetInterface
type applicationSets struct {
	*gentype.ClientWithList[*v1alpha1.ApplicationSet, *v1alpha1.ApplicationSetList]
}

// newApplicationSets returns a ApplicationSets
func newApplicationSets(c *ApisV1alpha1Client, namespace string) *applicationSets {
	return &applicationSets{
		gentype.NewClientWithList[*v1alpha1.ApplicationSet, *v1alpha1.ApplicationSetList](
			"applicationsets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.ApplicationSet { return &v1alpha1.ApplicationSet{} },
			func() *v1alpha1.ApplicationSetList { return &v1alpha1.ApplicationSetList{} }),
	}
}
